POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test",
  "author": "String",
  "url": "String",
  "userId": "630c8b4b2e7c1b8dca1ec9fa",
  "likes": 33
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "String",
  "password": "root"
}